
[terminal.shell]
program = "/opt/homebrew/bin/nu"
args = ["-c", "try { /opt/homebrew/bin/zellij a main } catch { try { /opt/homebrew/bin/zellij -s main } catch { /opt/homebrew/bin/zellij } }"]

[env]
TERM = "xterm-256color"

[window]
option_as_alt = "Both"

[font]
size = 13.25

[font.normal]
family = "JetBrainsMono Nerd Font"

[general]
live_config_reload = true
import = [
  "~/.config/alacritty/catppuccin-mocha.toml",
]

[terminal]
